spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/neviim}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:neviim}
    password: ${DB_PASSWORD:neviim}
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
