spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/neviim
    driver-class-name: org.postgresql.Driver
    username: neviim
    password: neviim
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
